-thank you so much and welcome
-this is just an incredibly exciting event for all of us in Google Cloud
-,for all of us at Google,
-..I would say
-you know the guy that was mic'ing me was telling me that there was a queue around the block
-,that we had a block buster, and I'm sorry for the queue,
-,but we're pretty happy to have all of you here to be at capacity at 10,000
-all the people live streaming
-I really regret the live streamers couldn't see the surround of that amazing animation that we just showed

-Google -- I mean 'cloud' -- does anybody not agree it's the biggest thing going on in I.T. right now?
-Woo!
-Google Cloud -- I mean the adoption of _cloud_ in general I believe it must be accelerating
-,I know at Google Cloud this year we've seen unbelievable acceleration
-,and the quality of our customer conversations are really changing
-for a while it was more:
-:"let's use BigQuery",
-,:"let's do our data analytics",
-,:"let's do a machine learning project"
-,but just 2 weeks ago I met with 5 customers over the course of the week
-,and 3 of them said "hey I want to do a full lift-and-shift",
-,I just want to move everything to the cloud
-,and it was only last September that we actually started calling ourselves Google Cloud
-..all that we do from the infrastructure to the workplace collaboration,
-.,productivity, and even the mobile devices in the enterprise

-It's been a remarkable year - our engineers have done over 500 releases
-,these are releases to get functionality to our customers
-,these are new innovations these are inventions
-,and just ongoing improvement in all that we do
-..security, reliability, efficiencies...

-Cloud is just an incredible place to be working right now
-,it's basically revolutionising...
-,it's sort of where a lot of the revolution -- the digital revolution -- for every industry is going on
-In financial services, tremendous efficiencies in how data is processed
-,or how the banks can talk directly to their customers

-In health, we're seeing a revolution in diagnosis,
-,in prediction of patient outcomes
-,and retail -- particularly exciting area -- taking billions of dollars out as we revolutionise the store of the future

-Media, something Google is particularly well situated to do
-,and energy, manufacturing, optimising, reducing the energy usage
-,making the factories/the manufacturing more efficient

-It's incredibly exciting to be a part of this,
-,we have such interesting customers
-,we have a customer planet labs(?) that's taking pictures of the entire Earth every 3 hours
-,and that's going on Google Cloud
